name: Gentoo Stage1 For x86_64

#on:
#  schedule:
#  - cron: ""

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stage1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master    
    - name: bootstrap stage1
      run: |
        set -x        	
        ./ab.sh _test
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: packages
        release_name: Release ${{ github.ref }}
        body: Daily build


    - name: Upload stage3 file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./out/stage3.tar.bz2
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
