name: Gentoo Stage3 For x86_64

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master    
    - name: bootstrap stage1
      run: |
        set -x        	
        ./ab.sh _test
    - name: Stage1  packages
      uses: actions/upload-artifact@master
      with:
        name: Stage3 Files
        path: out/stage3.tar.bz2        

